# -*- coding: utf-8 -*-
"""Ajay Hotel booking analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KTbr3wHdVLgQmBtiLPIVQ7RNBLsTF-F3

# **Project Name**    - Hotel Booking Analysis

##### **Project Type**    - EDA
##### **Contribution**    - Individual

# **Project Summary -**

This dataset is related to Hotel bookings. What are the key factors people make their hotel booking. It can be related to aything like daily rates, weather, parking space, other hotel facilities. This dataset contains the information of city and resort hotels with the information of length of stay, the number of people including adults, childrens and babies, waiting time and other hotel facilities.

# **GitHub Link -**

Provide your GitHub Link here.

# **Problem Statement**

**BUSINESS PROBLEM OVERVIEW**

Hotel booking is generally depends on the availability of the hotels, daily rates and facilities provided to the curstomers.
While booking hotels customers have various options available online however what attracts them is the daily rates and available facilities. Also, customers look for availability of the rooms for the number of members they are making booking, length of stay, arrival date and previous cancellation history.

#### **Define Your Business Objective?**

Factors leads to hotel booking and reducing cancellations

# **General Guidelines** : -

1.   Well-structured, formatted, and commented code is required.
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits.
     
     The additional credits will have advantages over other students during Star Student selection.
       
             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.
        

```
# Chart visualization code
```
            

*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

5. You have to create at least 20 logical & meaningful charts having important insights.


[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule.

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries
"""

# Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""### Dataset Loading"""

#mount the dataset fro google drive
from google.colab import drive
drive.mount('/content/drive')

# Load Dataset
#store the path of the dataset in a variable
path = '/content/drive/MyDrive/Colab Notebooks/Hotel Bookings.csv'

#load the dataset through pandas
dataset = pd.read_csv(path)

"""### Dataset First View"""

# Dataset First Look
dataset.head()

"""### Dataset Rows & Columns count"""

# Dataset Rows & Columns count
dataset.shape

#creat a copy of dataset and assigning to df
df = dataset.copy()

"""### Dataset Information"""

# Dataset Info
df.info()

"""#### Duplicate Values"""

# Dataset Duplicate Value Count
df[df.duplicated()].shape

"""#### Missing Values/Null Values"""

# Missing Values/Null Values Count and sort for descending order to see the which column has most missing values
df.isnull().sum().sort_values(ascending =False)

"""With the above code we can see Company, agent, country and children column has missing values. Country has 112593, agent has 16340, country has 488 and children has 4 missing values"""

#replacing company coloumn missing values with 0
df['company'] = df['company'].fillna(0)
df.head()

#agent column also has numeric value
#replacing all Null values of agent column with 0
df['agent']=df['agent'].fillna(0)
df.head()

#replacing all null values of country column with its mode value and using inplace for a permanent chage
df['country']=df['country'].fillna(df['country'].mode().to_string())

"""Country column represent the different country codes. Hence, filled null values with mode"""

# replacing missing values of children column
df['children']=df['children'].fillna(df['children'].mean())

"""Replacing null values of children column with mean as it contains the count of childrens"""

# Visualizing the missing values
sns.heatmap(df.isnull())

"""### What did you know about your dataset?

The dataset contains information about hotel bookings. We have to analysie and find the factor that leads to hotel bookings and cancellation bookings. The cancellation depends of variour factors like facilitites provided by the hotel like parking spaces, meal and other things that make people like more convienent and also daily rates of the bookings.

## ***2. Understanding Your Variables***
"""

# Dataset Columns
df.columns

# Dataset Describe
df.describe()

"""### Variables Description

* **Hotel**: Type of hotel resort hotel or City Hotel
* **Is_canceled**: Status of booking, if it was canceled or not
* **lead_time**: number of days between the hotel booking date and actual arrival date
* **arrival_date_year**: Year of arrival date
* **arrival_date_month**: Month of arrival date
* **arrival_date_week_number**: Week number of arrival date
* **arrival_date_day_of_month**: Day of arrival date
* **stays_in_weekend_nights**: Number of weekend nights customer stayed in hotel
* **stays_in_week_nights**: Number of week nights customer stayed in hotel
* **adults**: Number of adults
* **children**: Number of childrens
* **babies**: Number of babies
* **meal**: Type of meal opted (BB: Bed & Breakfast, FB: Full Board(breakfast, lunch and dinner), HB: Half Board (Breakfast and Dinner normally), SC: self catering(no meal))
* **country**: Country code
* **market_segment**: Customer segment belongs to
* **distribution_channel**: how the customer accessed the stay - corporate, Direct, GDS, TA/TO
* **is_repeated_guest**: How many times customer has stayed in the same hotel before, whethen its a first time or not
* **previous_cancellations**: If previously booking was canceled or not
* **previous_bookings_not_canceled**: count of previous bookings
* **reserved_room_type**: type of room reserved
* **assigned_room_type**: Type of room assigned
* **booking_changes**: How many times changes made to booking
* **deposit_type**: Type of deposit
* **agent**: Booking made through agent
* **company**: Booked through company
* **days_in_waiting_list**: Number of days in waiting list
* **customer_type**: Type of customer
* **adr**: average daily rate
* **required_car_parking_spaces**: If car parking is required or not
* **total_of_special_requests**: Number of special additional requests
* **reservation_status**: status of reservation
* **reservation_status_date**: Date of reservation

### Check Unique Values for each variable.
"""

# Check Unique Values for each variable.
for i in df.columns.tolist():
  print('unique value in', i, 'is', dataset[i].nunique())

"""## 3. ***Data Wrangling***

### Data Wrangling Code
"""

# Write your code to make your dataset analysis ready.

#assigning all the canceled booking of both hotel type to variable canceled_booking_df
canceled_booking_df = df[df['is_canceled']==1]

#assigning all the not canceled booking of both hotel type to vairable not_canceled_booking_df
not_canceled_booking_df = df[df['is_canceled']==0]

#total booking count for each hotel type
pd.DataFrame(df.value_counts('hotel').reset_index())

#only canceled bookings groupby hotel type
pd.DataFrame(canceled_booking_df.groupby('hotel')['is_canceled'].value_counts().reset_index())

#not canceled bookings groupby hotel type
not_canceled_booking_df.groupby('hotel')['is_canceled'].value_counts().reset_index()

#total booking count for each hotel type with canceled booking count assigning to a variable hotel_count
hotel_count = df.groupby('hotel')['is_canceled'].agg(['count', 'sum']).reset_index()
hotel_count

#calculate which hotel has higher cancellation ratio and assigining the value to the column name cancel_ratio
hotel_count['cancel_ratio'] = hotel_count['sum'] / hotel_count['count']
hotel_count

"""With this we found the City hotel has more canceled bookings than Resort hotel. Its cancellation ratio is higher than resort hotel"""

#assigning all the resort hotel booking to a variable resort_hotel_df
resort_hotel_df = df[df['hotel']=='Resort Hotel']
# resort_hotel_df

#assigning all the city hotel booking to a variable city_hotel_df
city_hotel_df = df[df['hotel']=='City Hotel']
# city_hotel_df

# groupby all arrival_date_year not canceled bookings of all resort hotel
resort_hotel_df[resort_hotel_df['is_canceled']==0].groupby('arrival_date_year')['is_canceled'].value_counts().reset_index()

"""With this we found 2016 had more resort hotel bookings"""

# groupby all arrival_date_year canceled bookings of resort hotel
resort_hotel_df[resort_hotel_df['is_canceled']==1].groupby('arrival_date_year')['is_canceled'].value_counts().reset_index()

"""With this we 2016 and 2017 resort hotel had more cancellations"""

city_hotel_df[city_hotel_df['is_canceled']==0].groupby('arrival_date_year')['is_canceled'].value_counts().reset_index()

"""It shows 2016 had more city hotel bookings"""

city_hotel_df[city_hotel_df['is_canceled']==1].groupby('arrival_date_year')['is_canceled'].value_counts().reset_index()

"""in 2016 and 2017 city hotel had more cancellations"""

# assigning booking yearwise to the variable df_2015, df_2016, df_2017
df_2015= not_canceled_booking_df[not_canceled_booking_df['arrival_date_year']==2015]
df_2016 = not_canceled_booking_df[not_canceled_booking_df['arrival_date_year']==2016]
df_2017= not_canceled_booking_df[not_canceled_booking_df['arrival_date_year']==2017]

#groupby 2015 bookings with arrival_date_mont and assigned to a variable df_2015_mean
df_2015_mean = df_2015.groupby('arrival_date_month')['is_canceled'].value_counts().reset_index()
df_2015_mean

#calculating the month count has more booking that its year booking count mean
df_2015_mean[df_2015_mean['count']>df_2015_mean['count'].mean()]

#groupby 2016 bookings with arrival_date_mont and assigned to a variable df_2016_mean
df_2016_mean = df_2016.groupby('arrival_date_month')['is_canceled'].value_counts().reset_index()
df_2016_mean

#calculating the month count has more booking that its year booking count mean
df_2016_mean[df_2016_mean['count']>df_2016_mean['count'].mean()]

#groupby 2017 bookings with arrival_date_mont and assigned to a variable df_2017_mean
df_2017_mean = df_2017.groupby('arrival_date_month')['is_canceled'].value_counts().reset_index()
df_2017_mean

#calculating the month count has more booking that its year booking count mean
df_2017_mean[df_2017_mean['count']>df_2017_mean['count'].mean()]

"""With this we find out for yearwise bookings in 2015 October and September were the peak season. In 2016, from April to October were the peak season and In 2017, April to July were the peak season"""

# groupby all the bookings by country code in descending order and asigned to a variable country_df
country_df = not_canceled_booking_df.groupby('country')['is_canceled'].value_counts().reset_index().sort_values(by = 'count', ascending=False)

country_df[country_df['count']>country_df['count'].mean()]

"""With this we found most of the bookings were made from European country and Portugal had the highest bookings"""

# groupby repeated guest bookings with country code
not_canceled_booking_df[not_canceled_booking_df['is_repeated_guest']==1].groupby('country')['is_canceled'].value_counts().reset_index().sort_values(by = 'count', ascending = False)

"""With this we found most of the repeated guest were from Portugal with a count of 2724 bookings. However the count of repeated guest very less"""

# groupby all bookings by meal for each country
not_canceled_booking_df.groupby('meal')['country'].value_counts().reset_index().sort_values(by = 'count', ascending=False)

"""with this we found most of the guest prefred Bed and Breakfast meal"""

# groupby all the bookings with distribution_channel
not_canceled_booking_df.groupby('distribution_channel')['is_canceled'].value_counts().reset_index().sort_values(by = 'count', ascending= False)

"""Most customers access booking through TA/TO

### What all manipulations have you done and insights you found?

As per the research I found people prefred City hotels more than Reort hotels. The total Resort hotel booking were 33102 and City hotels bookings were 11122. There were bookings that customers canceled after making it. The cancelation ratio of City Hotels is more than the Resort Hotels. To get the factors customer prefers while making a booking. I initialize all canceled and not canceled bookings in different variables and find both hotel types Resort hotel and City hotel had most of their bookings in 2016 and most of their cancellation in 2016 and 2017. Then, I initialize the bookings yearwise and find the all the bookings monthwise and found April to October was the peak season in 2016. For 2017, it was April to August and for 2015, it was September to October. Most of the bookings were from European countires and they prefer Bed and Breakfast meal. The rebooking ratio as compare to fresh bookings were really low.

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1
"""

# Chart - 1 visualization code
df['hotel'].value_counts().plot.pie(x = 'City Hotel', y = 'Resort hotel', autopct="%1.1f%%", title = 'Hotel', figsize=(6,6))

"""##### 1. Why did you pick the specific chart?

The dataset contains the information about the booking of two hotel types Resort Hotel and City Hotel. Pie chart helps to compare the percentage of whole data. Hence, I used Pie chart to see the booking perentage of each hotel type

##### 2. What is/are the insight(s) found from the chart?

From the above Pie chart we can see City hotel has 66.4% of bookings while Resort hotel has 33.6% of bookings

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

From the above chart its shows Customer prefer city hotels more than Resort hotels. It doesn't have any negative impact on the business

#### Chart - 2
"""

# Chart - 2 visualization code
plt.figure(figsize=(12,6))
sns.countplot(x = 'arrival_date_month', hue = 'hotel', data = df, palette= ['r','g'])
plt.title('Months of Arrival')
plt.show()

"""##### 1. Why did you pick the specific chart?

Countplot chart shows the counting of observation of each category. To check which month has the maximum arriving. Countplot helps to count the bookings for each month. Thus, I used countplot to see the maximum arrival of the month.

##### 2. What is/are the insight(s) found from the chart?

From the above graph we can see, November to March were off peak season and April to August were the peak season

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Yes, it helps hotel owners to make the changes in the discount in the bookings that attract customers most in the peak season. With the help of above chart hotel owners will have an idea when they will have to do be extra prepar which give them more business.

#### Chart - 3
"""

# Chart - 3 visualization code
plt.figure(figsize=(10,6))
sns.countplot(x = 'arrival_date_year', hue = 'hotel', data = df, palette= ['g','y'])
plt.title('Year of arrival')
plt.show()

"""##### 1. Why did you pick the specific chart?

Countplot chart shows the counting of observation of each category. To check which year has the maximum arriving. Countplot helps to count the bookings for each year. Thus, I used countplot to see the maximum arrival of the Year.

##### 2. What is/are the insight(s) found from the chart?

From the above chart we can see peak year for both hotel type was 2016. Furthermore, Every year City hotel had more bookings than resort hotel.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

with the help of above graph hotel owners can finds out what they did specially in 2016 that gives them more bookings.

#### Chart - 4
"""

# Chart - 4 visualization code
sns.countplot(x = 'is_canceled', hue = 'hotel', data=df)
plt.title('Cancelation Status')

"""##### 1. Why did you pick the specific chart?

Countplot chart shows the counting of observation of each category. To check which hote type has more cancelation and more bookings. Countplot helps to count the bookings and cancelation for each hotel type. Thus, I used countplot to see the cancelation ratio for each hotel type.

##### 2. What is/are the insight(s) found from the chart?

In the above countplot graph we can see City hotel had more booking and cancelation than resort hotel.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

It helps to identify which hotel type has more cancelations and more bookings

#### Chart - 5
"""

# Chart - 5 visualization code
sns.barplot(x= list(df['country'].value_counts().head(10).index), y = list(df['country'].value_counts().head(10)))
plt.title('Highest guest count of each country')

"""##### 1. Why did you pick the specific chart?

Bar chart shows the relation between numeric and categoric variable. We need to find the country with highest visiter count. Hence, barplot shows the relation between the country and count of the visitors

##### 2. What is/are the insight(s) found from the chart?

The above chart shows most of the bookings were made from Portugal

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

It helps business to find the most visitors are from European countires, as we can see Portugal has the highest bookings followed by Great Britian

#### Chart - 6
"""

# Chart - 6 visualization code
number_of_guest = df.country.value_counts().head(10).plot(kind = 'bar')
for p in number_of_guest.patches:
  number_of_guest.annotate(str(p.get_height()), (p.get_x() * 1.005, p.get_height() * 1.005))

"""##### 1. Why did you pick the specific chart?

Bar chart shows the relation between numeric and categoric variable. We need to find the country with highest visiter count. Hence, barplot shows the relation between the country and count of the visitors

##### 2. What is/are the insight(s) found from the chart?

The most number of guest are from Portugal which we have observed from previous graph now from current graph it is observed that the guests are 48483

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

It helps business to find the most visitors are from European countires, as we can see Portugal has the highest bookings followed by Great Britian

#### Chart - 7
"""

# Chart - 7 visualization code
plt.figure(figsize=(12,6))
#not_canceled_booking_df is defined above in the data wrangling secton. checking which segment has made the most bookings
sns.countplot(x="market_segment", data = not_canceled_booking_df)
plt.title("Segments wise booking")

"""##### 1. Why did you pick the specific chart?

Countplot chart shows the counting of observation of each category. To check how customers prefer their stay, Countplot helps to give the count for each Market segment. Thus, I used countplot to see the maximum segment used by the customers.

##### 2. What is/are the insight(s) found from the chart?

Most of the market_segment used Online TA and Offline TA/TO channels which is travel agency and tour operator.Followed by Groups and direct channel.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

It helps business to understand which segment customers prefer the most. As we can see from the above graph most of the market_segment used Online TA and Offline TA/TO channels

#### Chart - 8
"""

# Chart - 8 visualization code
plt.title(" Percentgae (%) of repeated guests")
df['is_repeated_guest'].value_counts().plot.pie(x=0, y=1, shadow = True, autopct = '%1.1f%%')

"""##### 1. Why did you pick the specific chart?

Pie chart helps to compare the percentage of whole data. I wanted to check the percentage of repeated guest. Hence, I used Pie chart to see the booking perentage of repeated guest.

##### 2. What is/are the insight(s) found from the chart?

Repeated guests are very few which is only 3.2 %. In order to retained the guests , hotels/resort management should take feedback from the guests in order to imporve their services.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

It helps to check the repeated customer ratio to new customers. If customer choosing the same hotel again. It shows they had an amazing expierence while staying at hotel.

#### Chart - 9
"""

# Chart - 9 visualization code
plt.figure(figsize=(18,8))
sns.countplot(x='meal', data = df)
plt.title("Preferred Meal Type")
plt.xlabel('Meal Type')
plt.ylabel('Count')

"""##### 1. Why did you pick the specific chart?

Countplot chart shows the counting of observation of each category. To check what meal customers prefer most, Countplot helps to give the count for each Mel type. Thus, I used countplot to see the prefered meal by the customers.

##### 2. What is/are the insight(s) found from the chart?

BB meal is highly preferable by the customers followed by HB and SC meal

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Witht the above graph, it helps to know which meal is prefred by the customers so that hotel staff can serve more varieties in BB meal

#### Chart - 10
"""

# Chart - 10 visualization code
plt.title("Car parking")
df['required_car_parking_spaces'].value_counts().plot.pie(x=0, y=1, autopct = '%1.1f%%', shadow=True)

"""##### 1. Why did you pick the specific chart?

Pie chart helps to compare the percentage of whole data. I wanted to check the percentage of Car Parking required to customers or not. Hence, I used Pie chart to see the Car parking demands.

##### 2. What is/are the insight(s) found from the chart?

In the above graph we can see only 6.2% of the customers require car parking else 93.8% doesn't require any car parking.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

With we can see Hotels can make sure aabout the customers who travel with their own vehicles. Generally while making the hotel bookings this also effects people look for the parking space avaialable or not.

#### Chart - 11
"""

# Chart - 11 visualization code

# assigned all the months from January to December in a new variable new_order
new_order = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September',
             'October', 'November', 'December']

#groupby arrival date month of all the canceled bookings for city hotel by adr mean and assigned it to a variable City_monthly_adr
city_monthly_adr=canceled_booking_df[canceled_booking_df['hotel']=='City Hotel'].groupby('arrival_date_month')['adr'].mean().reindex(new_order).reset_index()

#groupby arrival date month of all the canceled bookings for resort hotel by adr mean and assigned it to a variable resort_monthly_adr
resort_monthly_adr = canceled_booking_df[canceled_booking_df['hotel']=='Resort Hotel'].groupby('arrival_date_month')['adr'].mean().reindex(new_order).reset_index()

#merge the both datafrmaes city_monthly_adr and resort_monthly_adr by coulmn arrival_date_month
monthly_adr = pd.merge(city_monthly_adr, resort_monthly_adr, on='arrival_date_month')

#rename the coumns with city_adr and monthly_adr
monthly_adr.columns = ['arrival_date_month', 'city_adr', 'resort_adr']

#create bar plot
sns.set(style="whitegrid")
plt.figure(figsize=(18,6))
sns.barplot(x='arrival_date_month', y='value', hue='variable', data=pd.melt(monthly_adr, ['arrival_date_month']))

# Set plot labels and title
plt.xlabel('Arrival Date Month')
plt.ylabel('ADR')
plt.title('City ADR vs Resort ADR by Month')
plt.legend(title='ADR Type')

"""##### 1. Why did you pick the specific chart?

Bar chart shows the relation between numeric and categoric variable. We need to find the changes in average daily rate for all canceled bookings between City and Resort Hotel. Hence, barplot shows the relation between the adr per month for City and Resort hotel

##### 2. What is/are the insight(s) found from the chart?

Customers choose the hotel if the bookings charges comes under the budget, in the above graph we can see the adr of city hotel is higher than resort hotels most of the time due to the reason City hotel has more cancellations than Resort hotel

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Daily rates and discounts attract the customers, It help business to control their daily rates. Customer don't wants to go out of budget. As we can see due to higher adr changes in city hotel it has more cancellations compared to resort hotel.

## **5. Solution to Business Objective**

#### What do you suggest the client to achieve Business Objective ?
Explain Briefly.

* Customer Prefer City Hotel more than Resort hotel
* City hotel Cancellation ratio is more than resort hotel
* Guest mostly prefer BB meal
* Guest access their stay through Online TA and Offline TA/TO channels
* Mostly European country Guest do the booking
* Customers prefer the hotel with more discounts
* Adr plays a major role in bookings

# **Conclusion**

1. The Pie Chart shows City hotel has 66.4% of bookings while Resort hotel has 33.6% of bookings
2. November to March were off peak season and April to August were the peak season
3. Peak year for both hotel type was 2016. Furthermore, Every year City hotel had more bookings than resort hotel.
4. City hotel had more bookings than Resort hotel, however, the cancellation ratio is also high for City hotel than resort hotel
5. Most of the guests came from european countries, with most of guests coming from Portugal.
6. The most number of guest made the booking is 48483 from Portugal
7. Most of the market_segment used Online TA and Offline TA/TO channels which is travel agency and tour operator.Followed by Groups and direct channel.
8. Repeated bookings are very few which is only 3.2 %, however the new bookings were 96.8%
9. BB meal is highly preferable by the customers followed by HB and SC meal
10. 6.2% of the customers require car parking else 93.8% doesn't require any car parking.
11. Adr creates an impact in bookings, if daily rate is higher than expected, customers don't prefer it and ending up cancelling their bookings.
12. Adr needs to be controlled in order to prevent cancellations

### ***Hurrah! You have successfully completed your EDA Capstone Project !!!***
"""